dist: focal
language: node_js
node_js:
  - "18"
install:
  - npm i -g grunt-cli
  - npm install
script:
  - npm run lint
  - npm test
deploy:
  provider: npm
  email: $PROJECT_OWNER_EMAIL
  api_key: $NPM_ACCESS_TOKEN
  on:
    tags: true
