dist: bionic
language: node_js
node_js:
  - "16"
install:
  - npm i -g grunt-cli
  - npm install
script:
  - grunt
  - npm test
deploy:
  provider: npm
  email: $PROJECT_OWNER_EMAIL
  api_key: $NPM_ACCESS_TOKEN
  on:
    tags: true
