dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "13"
install:
  - npm i -g grunt-cli
  - npm install
script:
  - grunt
  - npm test

