name: Node CI

on: [push]

jobs:
  build:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: npm install, build, and test
      run: |
        npm i
        npm i -g grunt-cli
        npm ci
        npm run build --if-present
        npm run lint
        npm test
      env:
        CI: true
